-- MySQL Script generated by MySQL Workbench
-- Thu Sep 22 21:26:38 2022
-- Model: pampa Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pampa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pampa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pampa` ;
USE `pampa` ;

-- -----------------------------------------------------
-- Table `pampa`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pampa`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `cnpj` INT NULL,
  `nomeFantasia` VARCHAR(225) NULL,
  `emailEmpresa` VARCHAR(225) NULL,
  `enderecoEmpresa` VARCHAR(225) NULL,
  `contato` INT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pampa`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pampa`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(225) NULL,
  `cpf` INT NULL,
  `telefone` INT NULL,
  `email` VARCHAR(225) NULL,
  `endereco` VARCHAR(225) NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pampa`.`Pessoa_has_Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pampa`.`Pessoa_has_Empresa` (
  `Pessoa_idPessoa` INT NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`Pessoa_idPessoa`, `Empresa_idEmpresa`),
  INDEX `fk_Pessoa_has_Empresa_Empresa1_idx` (`Empresa_idEmpresa` ASC),
  INDEX `fk_Pessoa_has_Empresa_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Pessoa_has_Empresa_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `pampa`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Empresa_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `pampa`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pampa`.`Boletos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pampa`.`Boletos` (
  `idBoleto` INT NOT NULL AUTO_INCREMENT,
  `valorBoleto` FLOAT NULL,
  `data` DATE NULL,
  `dataVencimento` DATE NULL,
  `nomeCliente` VARCHAR(225) NULL,
  `cpf` INT NULL,
  PRIMARY KEY (`idBoleto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pampa`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pampa`.`Contrato` (
  `idContrato` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `cidade` VARCHAR(225) NULL,
  `Boletos_idBoleto` INT NOT NULL,
  PRIMARY KEY (`idContrato`, `Boletos_idBoleto`),
  INDEX `fk_Contrato_Boletos1_idx` (`Boletos_idBoleto` ASC),
  CONSTRAINT `fk_Contrato_Boletos1`
    FOREIGN KEY (`Boletos_idBoleto`)
    REFERENCES `pampa`.`Boletos` (`idBoleto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pampa`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pampa`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Imovel_idImovel` INT NOT NULL,
  `Contrato_idContrato` INT NOT NULL,
  `Contrato_Boletos_idBoleto` INT NOT NULL,
  `Pessoa_has_Empresa_Pessoa_idPessoa` INT NOT NULL,
  `Pessoa_has_Empresa_Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Imovel1_idx` (`Imovel_idImovel` ASC),
  INDEX `fk_Cliente_Contrato1_idx` (`Contrato_idContrato` ASC, `Contrato_Boletos_idBoleto` ASC),
  INDEX `fk_Cliente_Pessoa_has_Empresa1_idx` (`Pessoa_has_Empresa_Pessoa_idPessoa` ASC, `Pessoa_has_Empresa_Empresa_idEmpresa` ASC),
  CONSTRAINT `fk_Cliente_Imovel1`
    FOREIGN KEY (`Imovel_idImovel`)
    REFERENCES `pampa`.`Imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Contrato1`
    FOREIGN KEY (`Contrato_idContrato` , `Contrato_Boletos_idBoleto`)
    REFERENCES `pampa`.`Contrato` (`idContrato` , `Boletos_idBoleto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Pessoa_has_Empresa1`
    FOREIGN KEY (`Pessoa_has_Empresa_Pessoa_idPessoa` , `Pessoa_has_Empresa_Empresa_idEmpresa`)
    REFERENCES `pampa`.`Pessoa_has_Empresa` (`Pessoa_idPessoa` , `Empresa_idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pampa`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pampa`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(225) NULL,
  `senha` VARCHAR(225) NULL,
  `estadoLogin` TINYINT(1) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idLogin`, `Cliente_idCliente`),
  INDEX `fk_Login_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Login_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `pampa`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pampa`.`Corretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pampa`.`Corretor` (
  `idCorretor` INT NOT NULL AUTO_INCREMENT,
  `creci` VARCHAR(225) NULL,
  `Pessoa_has_Empresa_Pessoa_idPessoa` INT NOT NULL,
  `Pessoa_has_Empresa_Empresa_idEmpresa` INT NOT NULL,
  `Login_idLogin` INT NOT NULL,
  `Login_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCorretor`, `Login_idLogin`, `Login_Cliente_idCliente`),
  INDEX `fk_Corretor_Pessoa_has_Empresa1_idx` (`Pessoa_has_Empresa_Pessoa_idPessoa` ASC, `Pessoa_has_Empresa_Empresa_idEmpresa` ASC),
  INDEX `fk_Corretor_Login1_idx` (`Login_idLogin` ASC, `Login_Cliente_idCliente` ASC),
  CONSTRAINT `fk_Corretor_Pessoa_has_Empresa1`
    FOREIGN KEY (`Pessoa_has_Empresa_Pessoa_idPessoa` , `Pessoa_has_Empresa_Empresa_idEmpresa`)
    REFERENCES `pampa`.`Pessoa_has_Empresa` (`Pessoa_idPessoa` , `Empresa_idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Corretor_Login1`
    FOREIGN KEY (`Login_idLogin` , `Login_Cliente_idCliente`)
    REFERENCES `pampa`.`Login` (`idLogin` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pampa`.`Imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pampa`.`Imovel` (
  `idImovel` INT NOT NULL AUTO_INCREMENT,
  `localizacao` VARCHAR(225) NULL,
  `corretorResp` VARCHAR(225) NULL,
  `proprietario` VARCHAR(225) NULL,
  `categoria` VARCHAR(225) NULL,
  `alugrVender` DOUBLE NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  `Corretor_idCorretor` INT NOT NULL,
  PRIMARY KEY (`idImovel`, `Empresa_idEmpresa`, `Corretor_idCorretor`),
  INDEX `fk_Imovel_Empresa1_idx` (`Empresa_idEmpresa` ASC),
  INDEX `fk_Imovel_Corretor1_idx` (`Corretor_idCorretor` ASC),
  CONSTRAINT `fk_Imovel_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `pampa`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imovel_Corretor1`
    FOREIGN KEY (`Corretor_idCorretor`)
    REFERENCES `pampa`.`Corretor` (`idCorretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;