const price = (price) => {
  Number.prototype.format = function (n, x) {
    var re = "\\d(?=(\\d{" + (x || 3) + "})+" + (n > 0 ? "\\." : "$") + ")";
    return this.toFixed(Math.max(0, ~~n)).replace(new RegExp(re, "g"), "$&,");
  };
  return price.format();
};

const listing = [
  {
    id: 1,
    title: "Apartamento para Alugar",
    slug: "apartment-for-rent",
    price: price(350000),
    location: "Brasil",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Gabriel Fogaca",
      image: "agent1.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Brasil Westlands",
      county: "Brasil",
      city: "Brasil",
      street: "Tengecha St",
      area: "Nairobi",
    },

    featured: true,
    type: "rental",
    listedIn: "Aluguel",
    category: "Apartments",
  },
  {
    id: 2,
    title: "Casa a venda",
    slug: "house-for-sell",
    price: price(25000),
    location: "Nakuru",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly",
    images: ["image8.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Tiago Dornelles",
      image: "agent3.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Brasil Westlands",
      county: "Brasil",
      city: "Brasil",
      street: "Tengecha St",
      area: "Brasil"
    },
    featured: true,
    type: "rental",
    listedIn: "Aluguel",
    category: "Offices",
  },
  {
    id: 3,
    title: "Apartamento em Ijui",
    slug: "apartment-in-Brasil",
    price: price(31000),
    location: "Brasil",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly",
    images: ["image7.jpg", "image3.jpg", "image2.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Gabriel Fogaca",
      image: "agent4.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Brasil Westlands",
      county: "Brasil",
      city: "Brasil",
      street: "Tengecha St",
      area: "Nairobi",
    },
    featured: true,
    type: "rental",
    listedIn: "Venda",
    category: "Offices",
  },
  {
    id: 4,
    title: "Casa no Assis Brasil",
    slug: "renoveted-house-for-sale",
    price: price(35000),
    location: "Brasil",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly",
    images: ["image4.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Ranieri da Silva",
      image: "agent2.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Brasil Westlands",
      county: "Kisii",
      city: "Brasil",
      street: "Tengecha St",
      area: "Nairobi",
    },
    featured: true,
    type: "sale",
    listedIn: "Venda",
    category: "Houses",
  },
  {
    id: 5,
    title: "Casa no Alvorada",
    slug: "house-in-nakuru",
    price: price(35000),
    location: "Brasil",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Ranieri da Silva",
      image: "agent1.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Brasil Westlands",
      county: "Brasil",
      city: "Brasil",
      street: "Tengecha St",
      area: "Nairobi",
    },
    featured: true,
    type: "sale",
    listedIn: "Venda",
    category: "Retails",
  },
  {
    id: 6,
    title: "Apartamento para Alugar",
    slug: "apartment-for-rent",
    price: price(35000),
    location: "Brasil",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Tiago Dornelles",
      image: "agent2.jpg",
    },
    features: {
      bedrooms: 10,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Brasil Westlands",
      county: "Brasil",
      city: "Brasil",
      street: "Tengecha St",
      area: "Nairobi",
    },
    featured: true,
    type: "sale",
    listedIn: "Aluguel",
    category: "Apartments",
  },
  {
    id: 7,
    title: "Apartamento Figueiredo",
    slug: "offices-for-rent",
    price: price(35000),
    location: "Brasil",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Laura Ray",
      image: "agent1.jpg",
    },
    features: {
      bedrooms: 8,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Brasil Westlands",
      county: "Brasil",
      city: "Brasil",
      street: "Tengecha St",
      area: "Nairobi",
    },
    featured: true,
    type: "rental",
    listedIn: "Aluguel",
    category: "Houses",
  },
  {
    id: 8,
    title: "Apartamento para Alugar",
    slug: "apartmen-for-rent",
    price: price(35000),
    location: "Brasil",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Gabriel Fogaca",
      image: "agent4.jpg",
    },
    features: {
      bedrooms: 4,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Brasil Westlands",
      county: "Brasil",
      city: "Brasil",
      street: "Tengecha St",
      area: "Nairobi",
    },
    featured: true,
    type: "rental",
    listedIn: "Aluguel",
    category: "Houses",
  },
  {
    id: 9,
    title: "Apartamento para Alugar",
    slug: "apartment-for-rent",
    price: price(35000),
    location: "Brasil",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Edward Johnson",
      image: "agent4.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Brasil Westlands",
      county: "Brasil",
      city: "Brasil",
      street: "Tengecha St",
      area: "Nairobi",
    },
    featured: true,
    type: "sale",
    listedIn: "Aluguel",
    category: "Retails",
  },
];

export default listing;
